name: AsyncFunctionReload
version: '${version}'
main: com.gmail.necnionch.myplugin.asyncfunctionreload.bukkit.AsyncFunctionReload
api-version: 1.19  # only
authors: [ Necnion8 ]

commands:
  functionsreload:
    aliases: [frl]
    permission: asyncfunctionreload.command.functionsreload

permissions:
  asyncfunctionreload.command.functionsreload:
    default: op
